[workspace]
authors = ["Alex Zhang <alexzhang1030@foxmail.com>"]
channels = ["robostack-humble", "conda-forge"]
name = "ros2_scaffold"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-humble-turtlesim = ">=1.4.2,<2"
ros-humble-desktop = ">=0.10.0,<0.11"
