[workspace]
authors = ["Alex Zhang <alexzhang1030@foxmail.com>"]
channels = ["robostack-humble", "conda-forge"]
name = "ros2_scaffold"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "colcon build --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"

[dependencies]
ros-humble-turtlesim = ">=1.4.2,<2"
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
